               #cffC6E2FF#b#uWelcome to the FlyFF V15 Beta Test!#nb#nu
We sincerely hope you enjoy the new features, changes, and bug fixes we are bringing to you with this new update.  For any questions, concerns, or comments regarding this Beta Test, please visit our forums at:

                    #bhttp://flyff-forum.gpotato.com/#nb

To submit bugs, report concerns, suggest improvements, or tell us what you had for breakfast, please email #bflyffbugs@gala-net.com#nb.  We will be checking these submissions daily during the Beta Test.

Happy FlyFFing,

#bThe FlyFF Game Master Team#nb









